# Generated by Django 5.1.7 on 2025-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombrearea', models.CharField(max_length=50)),
                ('descripcionarea', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('revista', models.CharField(max_length=30)),
                ('pais', models.CharField(max_length=20)),
                ('aniopublicacion', models.DateField()),
                ('url', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'articulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carreras',
            fields=[
                ('idcarreras', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecarrera', models.CharField(max_length=40)),
                ('nombreuniversidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'carreras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetArt',
            fields=[
                ('iddetart', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetEventos',
            fields=[
                ('iddeteventos', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'deteventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetHerramienta',
            fields=[
                ('iddetherramienta', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detherramienta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetLineas',
            fields=[
                ('iddetlineas', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detlineas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetProy',
            fields=[
                ('iddetproy', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'detproy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('idespecialidades', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('idestudiantes', models.AutoField(primary_key=True, serialize=False)),
                ('nombreestudiante', models.CharField(max_length=50)),
                ('apellidoestudiante', models.CharField(max_length=50)),
                ('emailestudiante', models.CharField(max_length=50)),
                ('telefonoestudiante', models.CharField(max_length=20)),
                ('fechaingreso', models.DateField()),
                ('fechafincontrato', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('idevento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreevento', models.CharField(max_length=100)),
                ('lugarevento', models.CharField(max_length=100)),
                ('fechaevento', models.DateField()),
                ('duracionevento', models.CharField(blank=True, max_length=50, null=True)),
                ('empresainvitante', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'eventos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('idherramientas', models.AutoField(primary_key=True, serialize=False)),
                ('nombreherramienta', models.CharField(max_length=255)),
                ('tipoherramienta', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'herramientas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investigadores',
            fields=[
                ('idinvestigadores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'investigadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lineas',
            fields=[
                ('idlineas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaapertura', models.DateField()),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lineas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelEdu',
            fields=[
                ('idniveledu', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'niveledu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelSni',
            fields=[
                ('idnivelsni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nivelsni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('idpermiso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=20)),
                ('rol', models.IntegerField()),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('idproyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproyecto', models.CharField(max_length=255)),
                ('descripcionproyecto', models.TextField(blank=True, null=True)),
                ('fechainicio', models.DateField()),
                ('fechatermino', models.DateField()),
            ],
            options={
                'db_table': 'proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sni',
            fields=[
                ('idsni', models.AutoField(primary_key=True, serialize=False)),
                ('fechaingreso', models.DateField()),
                ('fecharenovacion', models.DateField()),
            ],
            options={
                'db_table': 'sni',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEstudiante',
            fields=[
                ('idtipoestudiante', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionestudiante', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoestudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('idtipoevento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreevento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipoevento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('idunidades', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
