# Generated by Django 5.1.7 on 2025-03-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'managed': False, 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
