# Generated by Django 5.1.7 on 2025-03-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_estudiantes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'managed': False},
        ),
    ]
