# Generated by Django 5.1.7 on 2025-03-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tipoestudiante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'managed': False, 'verbose_name_plural': 'Estudiantes'},
        ),
    ]
