# Generated by Django 5.1.7 on 2025-03-30 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_estudiantes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveledu',
            options={'managed': False, 'verbose_name': 'Nivel Educativo', 'verbose_name_plural': 'Niveles Educativos'},
        ),
    ]
