# Generated by Django 5.1.7 on 2025-03-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_niveledu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deteventos',
            options={'managed': False, 'verbose_name': 'Detalle de Evento', 'verbose_name_plural': 'Detalles de Eventos'},
        ),
        migrations.AlterModelTable(
            name='investigadores',
            table='lineas',
        ),
    ]
