# Generated by Django 5.1.7 on 2025-03-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_deteventos_options_alter_investigadores_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineas',
            options={'managed': False, 'verbose_name_plural': 'Líneas'},
        ),
    ]
