# Generated by Django 5.1.7 on 2025-03-30 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_lineas_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineas',
            options={'managed': False},
        ),
    ]
