# Generated by Django 5.1.7 on 2025-04-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_lineas_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='investigadores',
            table='investigadores',
        ),
    ]
