# Generated by Django 5.2 on 2025-05-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_investigadores_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='articulos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='carreras',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='deteventos',
            options={'managed': True, 'verbose_name': 'Detalle de Evento', 'verbose_name_plural': 'Detalles de Eventos'},
        ),
        migrations.AlterModelOptions(
            name='detherramienta',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detlineas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='detproy',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='especialidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='estudiantes',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='herramientas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='investigadores',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lineas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='niveledu',
            options={'managed': True, 'verbose_name': 'Nivel Educativo', 'verbose_name_plural': 'Niveles Educativos'},
        ),
        migrations.AlterModelOptions(
            name='nivelsni',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='permisos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sni',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipoestudiante',
            options={'managed': True, 'verbose_name_plural': 'Tipos de Estudiante'},
        ),
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='unidades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
    ]
