# Generated by Django 5.1.6 on 2025-05-09 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_area_options_alter_articulos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoestudiante',
            name='descripcionestudiante',
        ),
        migrations.AddField(
            model_name='area',
            name='idunidades',
            field=models.ForeignKey(db_column='idunidades', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.unidades'),
        ),
        migrations.AddField(
            model_name='detart',
            name='idarticulo',
            field=models.ForeignKey(db_column='idarticulo', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.articulos'),
        ),
        migrations.AddField(
            model_name='detart',
            name='idinvestigador',
            field=models.ForeignKey(db_column='idinvestigadores', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.investigadores'),
        ),
        migrations.AddField(
            model_name='deteventos',
            name='idevento',
            field=models.ForeignKey(db_column='idevento', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.eventos'),
        ),
        migrations.AddField(
            model_name='deteventos',
            name='idinvestigadores',
            field=models.ForeignKey(db_column='idinvestigadores', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.investigadores'),
        ),
        migrations.AddField(
            model_name='detherramienta',
            name='idherramientas',
            field=models.ForeignKey(db_column='idherramientas', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.herramientas'),
        ),
        migrations.AddField(
            model_name='detherramienta',
            name='idproyecto',
            field=models.ForeignKey(db_column='idproyecto', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.proyectos'),
        ),
        migrations.AddField(
            model_name='detlineas',
            name='idinvestigadores',
            field=models.ForeignKey(db_column='idinvestigadores', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.investigadores'),
        ),
        migrations.AddField(
            model_name='detlineas',
            name='idlineas',
            field=models.ForeignKey(db_column='idlineas', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.lineas'),
        ),
        migrations.AddField(
            model_name='detproy',
            name='idinvestigadores',
            field=models.ForeignKey(db_column='idinvestigadores', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.investigadores'),
        ),
        migrations.AddField(
            model_name='detproy',
            name='idproyecto',
            field=models.ForeignKey(db_column='idproyecto', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.proyectos'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='idcarreras',
            field=models.ForeignKey(db_column='idcarreras', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.carreras'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='idinvestigadores',
            field=models.ForeignKey(db_column='idinvestigadores', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.investigadores'),
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='idtipoestudiante',
            field=models.ForeignKey(db_column='idtipoestudiante', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tipoestudiante'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='idtipoevento',
            field=models.ForeignKey(db_column='idtipoevento', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tipoevento'),
        ),
        migrations.AddField(
            model_name='investigadores',
            name='idarea',
            field=models.ForeignKey(db_column='idarea', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.area'),
        ),
        migrations.AddField(
            model_name='investigadores',
            name='idniveledu',
            field=models.ForeignKey(db_column='idniveledu', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.niveledu'),
        ),
        migrations.AddField(
            model_name='niveledu',
            name='idespecialidades',
            field=models.ForeignKey(db_column='idespecialidades', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.especialidades'),
        ),
        migrations.AddField(
            model_name='sni',
            name='idinvestigadores',
            field=models.ForeignKey(db_column='idinvestigadores', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.investigadores'),
        ),
        migrations.AddField(
            model_name='sni',
            name='idnivelsni',
            field=models.ForeignKey(db_column='idnivelsni', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.nivelsni'),
        ),
        migrations.AddField(
            model_name='tipoestudiante',
            name='descripcion',
            field=models.CharField(default='Valor por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='idpermiso',
            field=models.ForeignKey(blank=True, db_column='idpermiso', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.permisos'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='fechafincontrato',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='telefonoestudiante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='duracionevento',
            field=models.CharField(blank=True, db_column='duracionevento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='empresainvitante',
            field=models.CharField(blank=True, db_column='empresainvitante', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fechaevento',
            field=models.DateField(db_column='fechaevento'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='idevento',
            field=models.AutoField(db_column='idevento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='lugarevento',
            field=models.CharField(db_column='lugarevento', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombreevento',
            field=models.CharField(db_column='nombreevento', max_length=100),
        ),
        migrations.AlterField(
            model_name='investigadores',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='investigadores',
            name='puesto',
            field=models.CharField(default='Investigador', max_length=50),
        ),
        migrations.AlterField(
            model_name='lineas',
            name='idlineas',
            field=models.AutoField(db_column='idlineas', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Investigador'), (3, 'Estudiante'), (4, 'Usuario General')]),
        ),
        migrations.AlterField(
            model_name='tipoestudiante',
            name='idtipoestudiante',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
